# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Emanuel', :city => cities.first)

Country.create(:name => 'AFGHANISTAN', :iso2 => 'AF', :iso3 => 'AFG')
Country.create(:name => 'ALAND ISLANDS', :iso2 => 'AX', :iso3 => 'ALA')
Country.create(:name => 'ALBANIA', :iso2 => 'AL', :iso3 => 'ALB')
Country.create(:name => 'ALGERIA', :iso2 => 'DZ', :iso3 => 'DZA')
Country.create(:name => 'AMERICAN SAMOA', :iso2 => 'AS', :iso3 => 'ASM')
Country.create(:name => 'ANDORRA', :iso2 => 'AD', :iso3 => 'AND')
Country.create(:name => 'ANGOLA', :iso2 => 'AO', :iso3 => 'AGO')
Country.create(:name => 'ANGUILLA', :iso2 => 'AI', :iso3 => 'AIA')
Country.create(:name => 'ANTARCTICA', :iso2 => 'AQ', :iso3 => '')
Country.create(:name => 'ANTIGUA AND BARBUDA', :iso2 => 'AG', :iso3 => 'ATG')
Country.create(:name => 'ARGENTINA', :iso2 => 'AR', :iso3 => 'ARG')
Country.create(:name => 'ARMENIA', :iso2 => 'AM', :iso3 => 'ARM')
Country.create(:name => 'ARUBA', :iso2 => 'AW', :iso3 => 'ABW')
Country.create(:name => 'AUSTRALIA', :iso2 => 'AU', :iso3 => 'AUS')
Country.create(:name => 'AUSTRIA', :iso2 => 'AT', :iso3 => 'AUT')
Country.create(:name => 'AZERBAIJAN', :iso2 => 'AZ', :iso3 => 'AZE')
Country.create(:name => 'BAHAMAS', :iso2 => 'BS', :iso3 => 'BHS')
Country.create(:name => 'BAHRAIN', :iso2 => 'BH', :iso3 => 'BHR')
Country.create(:name => 'BANGLADESH', :iso2 => 'BD', :iso3 => 'BGD')
Country.create(:name => 'BARBADOS', :iso2 => 'BB', :iso3 => 'BRB')
Country.create(:name => 'BELARUS', :iso2 => 'BY', :iso3 => 'BLR')
Country.create(:name => 'BELGIUM', :iso2 => 'BE', :iso3 => 'BEL')
Country.create(:name => 'BELIZE', :iso2 => 'BZ', :iso3 => 'BLZ')
Country.create(:name => 'BENIN', :iso2 => 'BJ', :iso3 => 'BEN')
Country.create(:name => 'BERMUDA', :iso2 => 'BM', :iso3 => 'BMU')
Country.create(:name => 'BHUTAN', :iso2 => 'BT', :iso3 => 'BTN')
Country.create(:name => 'BOLIVIA, PLURINATIONAL STATE OF', :iso2 => 'BO', :iso3 => 'BOL')
Country.create(:name => 'BONAIRE, SINT EUSTATIUS AND SABA', :iso2 => 'BQ', :iso3 => 'BES')
Country.create(:name => 'BOSNIA AND HERZEGOVINA', :iso2 => 'BA', :iso3 => 'BIH')
Country.create(:name => 'BOTSWANA', :iso2 => 'BW', :iso3 => 'BWA')
Country.create(:name => 'BOUVET ISLAND', :iso2 => 'BV', :iso3 => '')
Country.create(:name => 'BRAZIL', :iso2 => 'BR', :iso3 => 'BRA')
Country.create(:name => 'BRITISH INDIAN OCEAN TERRITORY', :iso2 => 'IO', :iso3 => '')
Country.create(:name => 'BRUNEI DARUSSALAM', :iso2 => 'BN', :iso3 => 'BRN')
Country.create(:name => 'BULGARIA', :iso2 => 'BG', :iso3 => 'BGR')
Country.create(:name => 'BURKINA FASO', :iso2 => 'BF', :iso3 => 'BFA')
Country.create(:name => 'BURUNDI', :iso2 => 'BI', :iso3 => 'BDI')
Country.create(:name => 'CAMBODIA', :iso2 => 'KH', :iso3 => 'KHM')
Country.create(:name => 'CAMEROON', :iso2 => 'CM', :iso3 => 'CMR')
Country.create(:name => 'CANADA', :iso2 => 'CA', :iso3 => 'CAN')
Country.create(:name => 'CAPE VERDE', :iso2 => 'CV', :iso3 => 'CPV')
Country.create(:name => 'CAYMAN ISLANDS', :iso2 => 'KY', :iso3 => 'CYM')
Country.create(:name => 'CENTRAL AFRICAN REPUBLIC', :iso2 => 'CF', :iso3 => 'CAF')
Country.create(:name => 'CHAD', :iso2 => 'TD', :iso3 => 'TCD')
Country.create(:name => 'CHILE', :iso2 => 'CL', :iso3 => 'CHL')
Country.create(:name => 'CHINA', :iso2 => 'CN', :iso3 => 'CHN')
Country.create(:name => 'CHRISTMAS ISLAND', :iso2 => 'CX', :iso3 => '')
Country.create(:name => 'COCOS (KEELING) ISLANDS', :iso2 => 'CC', :iso3 => '')
Country.create(:name => 'COLOMBIA', :iso2 => 'CO', :iso3 => 'COL')
Country.create(:name => 'COMOROS', :iso2 => 'KM', :iso3 => 'COM')
Country.create(:name => 'CONGO', :iso2 => 'CG', :iso3 => 'COD')
Country.create(:name => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', :iso2 => 'CD', :iso3 => '')
Country.create(:name => 'COOK ISLANDS', :iso2 => 'CK', :iso3 => 'COK')
Country.create(:name => 'COSTA RICA', :iso2 => 'CR', :iso3 => 'CRI')
Country.create(:name => 'COTE D\'IVOIRE', :iso2 => 'CI', :iso3 => 'CIV')
Country.create(:name => 'CROATIA', :iso2 => 'HR', :iso3 => 'HRV')
Country.create(:name => 'CUBA', :iso2 => 'CU', :iso3 => 'CUB')
Country.create(:name => 'CURACAO', :iso2 => 'CW', :iso3 => 'CUW')
Country.create(:name => 'CYPRUS', :iso2 => 'CY', :iso3 => 'CYP')
Country.create(:name => 'CZECH REPUBLIC', :iso2 => 'CZ', :iso3 => 'CZE')
Country.create(:name => 'DENMARK', :iso2 => 'DK', :iso3 => 'DNK')
Country.create(:name => 'DJIBOUTI', :iso2 => 'DJ', :iso3 => 'DJI')
Country.create(:name => 'DOMINICA', :iso2 => 'DM', :iso3 => 'DMA')
Country.create(:name => 'DOMINICAN REPUBLIC', :iso2 => 'DO', :iso3 => 'DOM')
Country.create(:name => 'ECUADOR', :iso2 => 'EC', :iso3 => 'ECU')
Country.create(:name => 'EGYPT', :iso2 => 'EG', :iso3 => 'EGY')
Country.create(:name => 'EL SALVADOR', :iso2 => 'SV', :iso3 => 'SLV')
Country.create(:name => 'EQUATORIAL GUINEA', :iso2 => 'GQ', :iso3 => 'GNQ')
Country.create(:name => 'ERITREA', :iso2 => 'ER', :iso3 => 'ERI')
Country.create(:name => 'ESTONIA', :iso2 => 'EE', :iso3 => 'EST')
Country.create(:name => 'ETHIOPIA', :iso2 => 'ET', :iso3 => 'ETH')
Country.create(:name => 'FALKLAND ISLANDS (MALVINAS)', :iso2 => 'FK', :iso3 => 'FLK')
Country.create(:name => 'FAROE ISLANDS', :iso2 => 'FO', :iso3 => 'FRO')
Country.create(:name => 'FIJI', :iso2 => 'FJ', :iso3 => 'FJI')
Country.create(:name => 'FINLAND', :iso2 => 'FI', :iso3 => 'FIN')
Country.create(:name => 'FRANCE', :iso2 => 'FR', :iso3 => 'FRA')
Country.create(:name => 'FRENCH GUIANA', :iso2 => 'GF', :iso3 => 'GUF')
Country.create(:name => 'FRENCH POLYNESIA', :iso2 => 'PF', :iso3 => 'PYF')
Country.create(:name => 'FRENCH SOUTHERN TERRITORIES', :iso2 => 'TF', :iso3 => '')
Country.create(:name => 'GABON', :iso2 => 'GA', :iso3 => 'GAB')
Country.create(:name => 'GAMBIA', :iso2 => 'GM', :iso3 => 'GMB')
Country.create(:name => 'GEORGIA', :iso2 => 'GE', :iso3 => 'GEO')
Country.create(:name => 'GERMANY', :iso2 => 'DE', :iso3 => 'DEU')
Country.create(:name => 'GHANA', :iso2 => 'GH', :iso3 => 'GHA')
Country.create(:name => 'GIBRALTAR', :iso2 => 'GI', :iso3 => 'GIB')
Country.create(:name => 'GREECE', :iso2 => 'GR', :iso3 => 'GRC')
Country.create(:name => 'GREENLAND', :iso2 => 'GL', :iso3 => 'GRL')
Country.create(:name => 'GRENADA', :iso2 => 'GD', :iso3 => 'GRD')
Country.create(:name => 'GUADELOUPE', :iso2 => 'GP', :iso3 => 'GLP')
Country.create(:name => 'GUAM', :iso2 => 'GU', :iso3 => 'GUM')
Country.create(:name => 'GUATEMALA', :iso2 => 'GT', :iso3 => 'GTM')
Country.create(:name => 'GUERNSEY', :iso2 => 'GG', :iso3 => '')
Country.create(:name => 'GUINEA', :iso2 => 'GN', :iso3 => 'GIN')
Country.create(:name => 'GUINEA-BISSAU', :iso2 => 'GW', :iso3 => 'GNB')
Country.create(:name => 'GUYANA', :iso2 => 'GY', :iso3 => 'GUY')
Country.create(:name => 'HAITI', :iso2 => 'HT', :iso3 => 'HTI')
Country.create(:name => 'HEARD ISLAND AND MCDONALD ISLANDS', :iso2 => 'HM', :iso3 => '')
Country.create(:name => 'HOLY SEE (VATICAN CITY STATE)', :iso2 => 'VA', :iso3 => 'VAT')
Country.create(:name => 'HONDURAS', :iso2 => 'HN', :iso3 => 'HND')
Country.create(:name => 'HONG KONG', :iso2 => 'HK', :iso3 => 'HKG')
Country.create(:name => 'HUNGARY', :iso2 => 'HU', :iso3 => 'HUN')
Country.create(:name => 'ICELAND', :iso2 => 'IS', :iso3 => 'ISL')
Country.create(:name => 'INDIA', :iso2 => 'IN', :iso3 => 'IND')
Country.create(:name => 'INDONESIA', :iso2 => 'ID', :iso3 => 'IDN')
Country.create(:name => 'IRAN, ISLAMIC REPUBLIC OF', :iso2 => 'IR', :iso3 => 'IRN')
Country.create(:name => 'IRAQ', :iso2 => 'IQ', :iso3 => 'IRQ')
Country.create(:name => 'IRELAND', :iso2 => 'IE', :iso3 => 'IRL')
Country.create(:name => 'ISLE OF MAN', :iso2 => 'IM', :iso3 => 'IMN')
Country.create(:name => 'ISRAEL', :iso2 => 'IL', :iso3 => 'ISR')
Country.create(:name => 'ITALY', :iso2 => 'IT', :iso3 => 'ITA')
Country.create(:name => 'JAMAICA', :iso2 => 'JM', :iso3 => 'JAM')
Country.create(:name => 'JAPAN', :iso2 => 'JP', :iso3 => 'JPN')
Country.create(:name => 'JERSEY', :iso2 => 'JE', :iso3 => '')
Country.create(:name => 'JORDAN', :iso2 => 'JO', :iso3 => 'JOR')
Country.create(:name => 'KAZAKHSTAN', :iso2 => 'KZ', :iso3 => 'KAZ')
Country.create(:name => 'KENYA', :iso2 => 'KE', :iso3 => 'KEN')
Country.create(:name => 'KIRIBATI', :iso2 => 'KI', :iso3 => 'KIR')
Country.create(:name => 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF', :iso2 => 'KP', :iso3 => 'PRK')
Country.create(:name => 'KOREA, REPUBLIC OF', :iso2 => 'KR', :iso3 => 'KOR')
Country.create(:name => 'KUWAIT', :iso2 => 'KW', :iso3 => 'KWT')
Country.create(:name => 'KYRGYZSTAN', :iso2 => 'KG', :iso3 => 'KGZ')
Country.create(:name => 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC', :iso2 => 'LA', :iso3 => 'LAO')
Country.create(:name => 'LATVIA', :iso2 => 'LV', :iso3 => 'LVA')
Country.create(:name => 'LEBANON', :iso2 => 'LB', :iso3 => 'LBN')
Country.create(:name => 'LESOTHO', :iso2 => 'LS', :iso3 => 'LSO')
Country.create(:name => 'LIBERIA', :iso2 => 'LR', :iso3 => 'LBR')
Country.create(:name => 'LIBYAN ARAB JAMAHIRIYA', :iso2 => 'LY', :iso3 => 'LBY')
Country.create(:name => 'LIECHTENSTEIN', :iso2 => 'LI', :iso3 => 'LIE')
Country.create(:name => 'LITHUANIA', :iso2 => 'LT', :iso3 => 'LTU')
Country.create(:name => 'LUXEMBOURG', :iso2 => 'LU', :iso3 => 'LUX')
Country.create(:name => 'MACAO', :iso2 => 'MO', :iso3 => 'MAC')
Country.create(:name => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', :iso2 => 'MK', :iso3 => 'MKD')
Country.create(:name => 'MADAGASCAR', :iso2 => 'MG', :iso3 => 'MDG')
Country.create(:name => 'MALAWI', :iso2 => 'MW', :iso3 => 'MWI')
Country.create(:name => 'MALAYSIA', :iso2 => 'MY', :iso3 => 'MYS')
Country.create(:name => 'MALDIVES', :iso2 => 'MV', :iso3 => 'MDV')
Country.create(:name => 'MALI', :iso2 => 'ML', :iso3 => 'MLI')
Country.create(:name => 'MALTA', :iso2 => 'MT', :iso3 => 'MLT')
Country.create(:name => 'MARSHALL ISLANDS', :iso2 => 'MH', :iso3 => 'MHL')
Country.create(:name => 'MARTINIQUE', :iso2 => 'MQ', :iso3 => 'MTQ')
Country.create(:name => 'MAURITANIA', :iso2 => 'MR', :iso3 => 'MRT')
Country.create(:name => 'MAURITIUS', :iso2 => 'MU', :iso3 => 'MUS')
Country.create(:name => 'MAYOTTE', :iso2 => 'YT', :iso3 => '')
Country.create(:name => 'MEXICO', :iso2 => 'MX', :iso3 => 'MEX')
Country.create(:name => 'MICRONESIA, FEDERATED STATES OF', :iso2 => 'FM', :iso3 => 'FSM')
Country.create(:name => 'MOLDOVA, REPUBLIC OF', :iso2 => 'MD', :iso3 => 'MDA')
Country.create(:name => 'MONACO', :iso2 => 'MC', :iso3 => 'MCO')
Country.create(:name => 'MONGOLIA', :iso2 => 'MN', :iso3 => 'MNG')
Country.create(:name => 'MONTENEGRO', :iso2 => 'ME', :iso3 => 'MNE')
Country.create(:name => 'MONTSERRAT', :iso2 => 'MS', :iso3 => 'MSR')
Country.create(:name => 'MOROCCO', :iso2 => 'MA', :iso3 => 'MAR')
Country.create(:name => 'MOZAMBIQUE', :iso2 => 'MZ', :iso3 => 'MOZ')
Country.create(:name => 'MYANMAR', :iso2 => 'MM', :iso3 => 'MMR')
Country.create(:name => 'NAMIBIA', :iso2 => 'NA', :iso3 => 'NAM')
Country.create(:name => 'NAURU', :iso2 => 'NR', :iso3 => 'NRU')
Country.create(:name => 'NEPAL', :iso2 => 'NP', :iso3 => 'NPL')
Country.create(:name => 'NETHERLANDS', :iso2 => 'NL', :iso3 => 'NLD')
Country.create(:name => 'NEW CALEDONIA', :iso2 => 'NC', :iso3 => 'NCL')
Country.create(:name => 'NEW ZEALAND', :iso2 => 'NZ', :iso3 => 'NZL')
Country.create(:name => 'NICARAGUA', :iso2 => 'NI', :iso3 => 'NIC')
Country.create(:name => 'NIGER', :iso2 => 'NE', :iso3 => 'NER')
Country.create(:name => 'NIGERIA', :iso2 => 'NG', :iso3 => 'NGA')
Country.create(:name => 'NIUE', :iso2 => 'NU', :iso3 => 'NIU')
Country.create(:name => 'NORFOLK ISLAND', :iso2 => 'NF', :iso3 => 'NFK')
Country.create(:name => 'NORTHERN MARIANA ISLANDS', :iso2 => 'MP', :iso3 => 'MNP')
Country.create(:name => 'NORWAY', :iso2 => 'NO', :iso3 => 'NOR')
Country.create(:name => 'OMAN', :iso2 => 'OM', :iso3 => 'OMN')
Country.create(:name => 'PAKISTAN', :iso2 => 'PK', :iso3 => 'PAK')
Country.create(:name => 'PALAU', :iso2 => 'PW', :iso3 => 'PLW')
Country.create(:name => 'PALESTINIAN TERRITORY, OCCUPIED', :iso2 => 'PS', :iso3 => 'PSE')
Country.create(:name => 'PANAMA', :iso2 => 'PA', :iso3 => 'PAN')
Country.create(:name => 'PAPUA NEW GUINEA', :iso2 => 'PG', :iso3 => 'PNG')
Country.create(:name => 'PARAGUAY', :iso2 => 'PY', :iso3 => 'PRY')
Country.create(:name => 'PERU', :iso2 => 'PE', :iso3 => 'PER')
Country.create(:name => 'PHILIPPINES', :iso2 => 'PH', :iso3 => 'PHL')
Country.create(:name => 'PITCAIRN', :iso2 => 'PN', :iso3 => 'PCN')
Country.create(:name => 'POLAND', :iso2 => 'PL', :iso3 => 'POL')
Country.create(:name => 'PORTUGAL', :iso2 => 'PT', :iso3 => 'PRT')
Country.create(:name => 'PUERTO RICO', :iso2 => 'PR', :iso3 => 'PRI')
Country.create(:name => 'QATAR', :iso2 => 'QA', :iso3 => 'QAT')
Country.create(:name => 'REUNION', :iso2 => 'RE', :iso3 => 'REU')
Country.create(:name => 'ROMANIA', :iso2 => 'RO', :iso3 => 'ROU')
Country.create(:name => 'RUSSIAN FEDERATION', :iso2 => 'RU', :iso3 => 'RUS')
Country.create(:name => 'RWANDA', :iso2 => 'RW', :iso3 => 'RWA')
Country.create(:name => 'SAINT BARTHELEMY', :iso2 => 'BL', :iso3 => 'BLM')
Country.create(:name => 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA', :iso2 => 'SH', :iso3 => 'SHN')
Country.create(:name => 'SAINT KITTS AND NEVIS', :iso2 => 'KN', :iso3 => 'KNA')
Country.create(:name => 'SAINT LUCIA', :iso2 => 'LC', :iso3 => 'LCA')
Country.create(:name => 'SAINT MARTIN (FRENCH PART)', :iso2 => 'MF', :iso3 => '')
Country.create(:name => 'SAINT PIERRE AND MIQUELON', :iso2 => 'PM', :iso3 => 'SPM')
Country.create(:name => 'SAINT VINCENT AND THE GRENADINES', :iso2 => 'VC', :iso3 => 'VCT')
Country.create(:name => 'SAMOA', :iso2 => 'WS', :iso3 => 'WSM')
Country.create(:name => 'SAN MARINO', :iso2 => 'SM', :iso3 => 'SMR')
Country.create(:name => 'SAO TOME AND PRINCIPE', :iso2 => 'ST', :iso3 => 'STP')
Country.create(:name => 'SAUDI ARABIA', :iso2 => 'SA', :iso3 => 'SAU')
Country.create(:name => 'SENEGAL', :iso2 => 'SN', :iso3 => 'SEN')
Country.create(:name => 'SERBIA', :iso2 => 'RS', :iso3 => 'SRB')
Country.create(:name => 'SEYCHELLES', :iso2 => 'SC', :iso3 => 'SYC')
Country.create(:name => 'SIERRA LEONE', :iso2 => 'SL', :iso3 => 'SLE')
Country.create(:name => 'SINGAPORE', :iso2 => 'SG', :iso3 => 'SGP')
Country.create(:name => 'SINT MAARTEN (DUTCH PART)', :iso2 => 'SX', :iso3 => '')
Country.create(:name => 'SLOVAKIA', :iso2 => 'SK', :iso3 => 'SVK')
Country.create(:name => 'SLOVENIA', :iso2 => 'SI', :iso3 => 'SVN')
Country.create(:name => 'SOLOMON ISLANDS', :iso2 => 'SB', :iso3 => 'SLB')
Country.create(:name => 'SOMALIA', :iso2 => 'SO', :iso3 => 'SOM')
Country.create(:name => 'SOUTH AFRICA', :iso2 => 'ZA', :iso3 => 'ZAF')
Country.create(:name => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', :iso2 => 'GS', :iso3 => '')
Country.create(:name => 'SPAIN', :iso2 => 'ES', :iso3 => 'ESP')
Country.create(:name => 'SRI LANKA', :iso2 => 'LK', :iso3 => 'LKA')
Country.create(:name => 'SUDAN', :iso2 => 'SD', :iso3 => 'SDN')
Country.create(:name => 'SURINAME', :iso2 => 'SR', :iso3 => 'SUR')
Country.create(:name => 'SVALBARD AND JAN MAYEN', :iso2 => 'SJ', :iso3 => 'SJM')
Country.create(:name => 'SWAZILAND', :iso2 => 'SZ', :iso3 => 'SWZ')
Country.create(:name => 'SWEDEN', :iso2 => 'SE', :iso3 => 'SWE')
Country.create(:name => 'SWITZERLAND', :iso2 => 'CH', :iso3 => 'CHE')
Country.create(:name => 'SYRIAN ARAB REPUBLIC', :iso2 => 'SY', :iso3 => 'SYR')
Country.create(:name => 'TAIWAN, PROVINCE OF CHINA', :iso2 => 'TW', :iso3 => '')
Country.create(:name => 'TAJIKISTAN', :iso2 => 'TJ', :iso3 => 'TJK')
Country.create(:name => 'TANZANIA, UNITED REPUBLIC OF', :iso2 => 'TZ', :iso3 => 'TZA')
Country.create(:name => 'THAILAND', :iso2 => 'TH', :iso3 => 'THA')
Country.create(:name => 'TIMOR-LESTE', :iso2 => 'TL', :iso3 => 'TLS')
Country.create(:name => 'TOGO', :iso2 => 'TG', :iso3 => 'TGO')
Country.create(:name => 'TOKELAU', :iso2 => 'TK', :iso3 => 'TKL')
Country.create(:name => 'TONGA', :iso2 => 'TO', :iso3 => 'TON')
Country.create(:name => 'TRINIDAD AND TOBAGO', :iso2 => 'TT', :iso3 => 'TTO')
Country.create(:name => 'TUNISIA', :iso2 => 'TN', :iso3 => 'TUN')
Country.create(:name => 'TURKEY', :iso2 => 'TR', :iso3 => 'TUR')
Country.create(:name => 'TURKMENISTAN', :iso2 => 'TM', :iso3 => 'TKM')
Country.create(:name => 'TURKS AND CAICOS ISLANDS', :iso2 => 'TC', :iso3 => 'TCA')
Country.create(:name => 'TUVALU', :iso2 => 'TV', :iso3 => 'TUV')
Country.create(:name => 'UGANDA', :iso2 => 'UG', :iso3 => 'UGA')
Country.create(:name => 'UKRAINE', :iso2 => 'UA', :iso3 => 'UKR')
Country.create(:name => 'UNITED ARAB EMIRATES', :iso2 => 'AE', :iso3 => 'ARE')
Country.create(:name => 'UNITED KINGDOM', :iso2 => 'GB', :iso3 => 'GBR')
Country.create(:name => 'UNITED STATES', :iso2 => 'US', :iso3 => 'USA')
Country.create(:name => 'UNITED STATES MINOR OUTLYING ISLANDS', :iso2 => 'UM', :iso3 => '')
Country.create(:name => 'URUGUAY', :iso2 => 'UY', :iso3 => 'URY')
Country.create(:name => 'UZBEKISTAN', :iso2 => 'UZ', :iso3 => 'UZB')
Country.create(:name => 'VANUATU', :iso2 => 'VU', :iso3 => 'VUT')
Country.create(:name => 'VENEZUELA, BOLIVARIAN REPUBLIC OF', :iso2 => 'VE', :iso3 => 'VEN')
Country.create(:name => 'VIET NAM', :iso2 => 'VN', :iso3 => 'VNM')
Country.create(:name => 'VIRGIN ISLANDS, BRITISH', :iso2 => 'VG', :iso3 => 'VGB')
Country.create(:name => 'VIRGIN ISLANDS, U.S.', :iso2 => 'VI', :iso3 => 'VIR')
Country.create(:name => 'WALLIS AND FUTUNA', :iso2 => 'WF', :iso3 => 'WLF')
Country.create(:name => 'WESTERN SAHARA', :iso2 => 'EH', :iso3 => 'ESH')
Country.create(:name => 'YEMEN', :iso2 => 'YE', :iso3 => 'YEM')
Country.create(:name => 'ZAMBIA', :iso2 => 'ZM', :iso3 => 'ZMB')
Country.create(:name => 'ZIMBABWE', :iso2 => 'ZW', :iso3 => 'ZWE')

BusinessStyle.create(:name => 'Style 1')
BusinessStyle.create(:name => 'Style 2')
BusinessStyle.create(:name => 'Style 3')

Audience.create(:name => 'Male')
Audience.create(:name => 'Female')

AgeGroup.create(:name => '15 under')
AgeGroup.create(:name => '15-25')
AgeGroup.create(:name => '25-40')
AgeGroup.create(:name => '40+')